---
name: Run the Python and R Tests

on:
  push:
    branches: [ main ]

jobs:
  run_python_tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/joejcollins/admiral-denver:latest
      options: --user root # needs to be root or the checkout fails.

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: false
          clean: true

      - name: Run Python tests.
        run: |
          make venv
          make test
...
